name: 📧 Daily ArXiv Paper Recommendations
on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  recommend-and-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ vars.REPOSITORY }}
          ref: ${{ vars.REF }}

      - name: Setup uv
        uses: astral-sh/setup-uv@v3
        with:
          version: '0.5.4'

      - name: Run script
        env:
          ZOTERO_ID: ${{ secrets.ZOTERO_ID }}
          ZOTERO_KEY: ${{ secrets.ZOTERO_KEY }}
          ZOTERO_IGNORE: ${{ vars.ZOTERO_IGNORE }}
          SEND_EMPTY: ${{ vars.SEND_EMPTY }}
          ARXIV_QUERY: ${{ vars.ARXIV_QUERY }}
          SMTP_SERVER: ${{ vars.SMTP_SERVER }}
          SMTP_PORT: ${{ vars.SMTP_PORT }}
          SENDER: ${{ vars.SENDER }}
          RECEIVER: ${{ vars.RECEIVER }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          MAX_PAPER_NUM: ${{ vars.MAX_PAPER_NUM }}
          USE_LLM_API: ${{ vars.USE_LLM_API }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_BASE: ${{ vars.OPENAI_API_BASE }}
          MODEL_NAME: ${{ vars.MODEL_NAME }}
          LANGUAGE: ${{ vars.LANGUAGE }}
        run: |
          uv run main.py
